create materialized view yj_finaleigen_aki_fluid as
  WITH diuretic_tmp AS (
      SELECT ydc.icustay_id, ydc.diuretic_ic, ydm.diuretic_im
      FROM (mimiciii.yj_diuretic_cv ydc
          LEFT JOIN mimiciii.yj_diuretic_mv ydm ON ((ydc.icustay_id = ydm.icustay_id)))
  ), diuretic AS (
      SELECT dt.icustay_id,
             CASE
               WHEN ((dt.diuretic_im = 1) OR (dt.diuretic_ic = 1)) THEN 1
               ELSE 0
                 END AS diuretic
      FROM diuretic_tmp dt
  ), addfluid AS (
      SELECT yaa.icustay_id, diuretic.diuretic, yaa.inputsum
      FROM (diuretic
          LEFT JOIN mimiciii.yj_addfluid_aki yaa ON ((diuretic.icustay_id = yaa.icustay_id)))
  ), final AS (
      SELECT yaf.akistarttime,
             yaf.creat,
             yaf.classlabel,
             yaf.icustay_id,
             yaf.hr_max,
             yaf.hr_min,
             yaf.hr_avg,
             yaf.hr_std,
             yaf.hr_mid,
             yaf.hr_25,
             yaf.hr_75,
             yaf.rr_max,
             yaf.rr_min,
             yaf.rr_avg,
             yaf.rr_std,
             yaf.rr_mid,
             yaf.rr_25,
             yaf.rr_75,
             yaf.sbp_max,
             yaf.sbp_min,
             yaf.sbp_avg,
             yaf.sbp_std,
             yaf.sbp_mid,
             yaf.sbp_25,
             yaf.sbp_75,
             yaf.dbp_max,
             yaf.dbp_min,
             yaf.dbp_avg,
             yaf.dbp_std,
             yaf.dbp_mid,
             yaf.dbp_25,
             yaf.dbp_75,
             yaf.mbp_max,
             yaf.mbp_min,
             yaf.mbp_avg,
             yaf.mbp_std,
             yaf.mbp_mid,
             yaf.mbp_25,
             yaf.mbp_75,
             yaf.si_max,
             yaf.si_min,
             yaf.si_avg,
             yaf.si_std,
             yaf.si_mid,
             yaf.si_25,
             yaf.si_75,
             yaf.spo2_max,
             yaf.spo2_min,
             yaf.spo2_avg,
             yaf.spo2_std,
             yaf.spo2_mid,
             yaf.spo2_25,
             yaf.spo2_75,
             yaf.tem_max,
             yaf.tem_min,
             yaf.tem_avg,
             yaf.tem_std,
             yaf.tem_mid,
             yaf.tem_25,
             yaf.tem_75,
             yaf.uo_max,
             yaf.uo_min,
             yaf.uo_avg,
             yaf.uo_std,
             yaf.uo_mid,
             yaf.uo_25,
             yaf.uo_75,
             yaf.uosum,
             yaf.gcs_max,
             yaf.gcs_min,
             yaf.gcs_avg,
             yaf.gcs_std,
             yaf.gcs_mid,
             yaf.gcs_25,
             yaf.gcs_75,
             yaf.height,
             yaf.weight,
             yaf.vaso,
             yaf.vent,
             yaf.age,
             yaf.gender,
             yaf.ethnicity,
             yaf.admission_type,
             yaf.hospital_expire_flag,
             yaf.lostime,
             addfluid.inputsum,
             addfluid.diuretic
      FROM (addfluid
          LEFT JOIN mimiciii.yj_aki_finaleigen yaf ON ((addfluid.icustay_id = yaf.icustay_id)))
  )
  SELECT final.akistarttime,
         final.creat,
         final.classlabel,
         final.icustay_id,
         final.hr_max,
         final.hr_min,
         final.hr_avg,
         final.hr_std,
         final.hr_mid,
         final.hr_25,
         final.hr_75,
         final.rr_max,
         final.rr_min,
         final.rr_avg,
         final.rr_std,
         final.rr_mid,
         final.rr_25,
         final.rr_75,
         final.sbp_max,
         final.sbp_min,
         final.sbp_avg,
         final.sbp_std,
         final.sbp_mid,
         final.sbp_25,
         final.sbp_75,
         final.dbp_max,
         final.dbp_min,
         final.dbp_avg,
         final.dbp_std,
         final.dbp_mid,
         final.dbp_25,
         final.dbp_75,
         final.mbp_max,
         final.mbp_min,
         final.mbp_avg,
         final.mbp_std,
         final.mbp_mid,
         final.mbp_25,
         final.mbp_75,
         final.si_max,
         final.si_min,
         final.si_avg,
         final.si_std,
         final.si_mid,
         final.si_25,
         final.si_75,
         final.spo2_max,
         final.spo2_min,
         final.spo2_avg,
         final.spo2_std,
         final.spo2_mid,
         final.spo2_25,
         final.spo2_75,
         final.tem_max,
         final.tem_min,
         final.tem_avg,
         final.tem_std,
         final.tem_mid,
         final.tem_25,
         final.tem_75,
         final.uo_max,
         final.uo_min,
         final.uo_avg,
         final.uo_std,
         final.uo_mid,
         final.uo_25,
         final.uo_75,
         final.uosum,
         final.gcs_max,
         final.gcs_min,
         final.gcs_avg,
         final.gcs_std,
         final.gcs_mid,
         final.gcs_25,
         final.gcs_75,
         final.height,
         final.weight,
         final.vaso,
         final.vent,
         final.age,
         final.gender,
         final.ethnicity,
         final.admission_type,
         final.hospital_expire_flag,
         final.lostime,
         final.inputsum,
         final.diuretic
  FROM final;

alter materialized view yj_finaleigen_aki_fluid
  owner to postgres;

